bookproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import crudapp.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', crudapp.views.home, name='home'),
    path('crudapp/', include('crudapp.urls')),
    path('shop/', include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('user/', include('user.urls')),
    path('accounts/', include('allauth.urls')),
    path('map/', include('map.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('', detail, name="detail"),
    path('add/<int:product_id>/', add, name="product_add"),
    path('remove/<int:product_id>/', remove, name="product_remove"),
]

map/urls.py
from django.urls import path
from .views import *

app_name = 'map'

urlpatterns = [
    path('search/', search, name="api_search"),
]

shop/urls.py
from django.urls import path
from .views import *

app_name = 'shop'

urlpatterns = [
    path('', show_list, name="list"),
    path('<int:id>/<product_slug>/', product_detail, name="product_detail"),
]

cart/forms.py
from django import forms

class AddProductForm(forms.Form):
    quantity = forms.IntegerField()
    is_update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)
    

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

from shop.models import Product
from .forms import AddProductForm
from .cart import Cart

@require_POST
def add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)

    form = AddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], is_update=cd['is_update'])
        
        return redirect('cart:detail')

def remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:detail')

def detail(request):
    cart = Cart(request)
    for product in cart:
        product['quantity_form'] = AddProductForm(initial={'quantity':product['quantity'],
        'is_update':True})
    return render(request, 'cart/detail.html', {'cart':cart})

cart/templates/cart/detail.html
{% extends 'base.html' %}

{% block content %}

<style>
    body {
        text-align: center;
        background-color: rgb(233, 231, 231);
    }

    .container2 {
      text-align: left;
      margin: 10px auto;
      padding: 40px;
      border-style: none;
      border-radius: 25px;
      border-width: 2px;
      background-color: white;
      font-family: Arial, Helvetica, sans-serif;
      width: 50%;
      display: inline-block;
    }

    #thumbnail {
        width: 100px;
        height: 150px;
        float: left;
        margin-right: 5%;
    }

    button a {
        text-decoration: none;
        color: black;
    }

    #delete {
        float: right;
    }

    .description {
        text-align: left;
    }

    a {
        text-decoration: none;
        color: rgb(90, 180, 90);
    }
</style>

{% for item in cart %}
<div class="container2">
{% with product=item.product %}

{% if product.image %}
    <img id="thumbnail" src="{{product.image.url}}" alt=""><br>
{% endif %}
<div class="description">
책명 : {{ product.name }}
<form action="{% url 'cart:product_add' product.id %}" method="post">
    {% csrf_token %}
    권수 : {{ item.quantity_form.quantity }}
    {{ item.quantity_form.is_update }}
    <input type="submit" value="수량 변경">
</form>
<br>
<p>가격 : {{ item.price|floatformat }}원</p>
<p>소계 : {{ item.total_price|floatformat }}원</p>
<a id="delete" href="{% url 'cart:product_remove' product.id %}">장바구니에서 삭제</a>
<br>
</div>

</div>
{% endwith %}
{% endfor %}

<p><b>총 금액 : {{ cart.get_product_total|floatformat }}원</b></p>

<button type="button" class="btn btn-outline-dark">
    <a href='{% url "shop:list" %}'>쇼핑 계속하기</a> 
</button>

{% endblock %}