bookproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import crudapp.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', crudapp.views.home, name='home'),
    path('crudapp/', include('crudapp.urls')),
    path('shop/', include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('user/', include('user.urls')),
    path('accounts/', include('allauth.urls')),
    path('map/', include('map.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

map/urls.py
from django.urls import path
from .views import *

app_name = 'map'

urlpatterns = [
    path('search/', search, name="api_search"),
]

user/urls.py
from django.urls import path
from .views import *

app_name = 'user'

urlpatterns = [
    path('login/', login_view, name="login"),
    path('logout', logout_view, name="logout"),
    path('register/', register_view, name="signup"),
    path('profile/update/', profile_update, name="update"),
    path('profile/delete', profile_delete, name="delete"),
    path('profile/<int:pk>/', profile_view, name='profile'),
    path('<int:pk>/follow/', follow, name='follow'),
]

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings

class CustomUser(AbstractUser): 
    profilePic = models.ImageField(upload_to="user/", blank=True, null=True)
    introduce =  models.TextField(blank=True, null=True)
    followers = models.ManyToManyField(
            settings.AUTH_USER_MODEL,
            related_name='followings'
        )

user/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import UserChangeForm
from .models import CustomUser
from django import forms

class RegisterForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'password1', 'password2', 'profilePic', 'introduce']

class CustomUserChangeForm(UserChangeForm):
    password = None        
    username = forms.CharField(label='아이디', widget=forms.TextInput(attrs={'readonly':'readonly'}))
    profilePic = forms.ImageField(label='프로필사진', required=False)
    introduce = forms.CharField(label='자기소개', required=False, widget=forms.Textarea)

    class Meta:
        model = CustomUser
        fields = ['username', 'profilePic', 'introduce']

user/views.py
from .models import CustomUser
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm 
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .forms import RegisterForm 
from .forms import CustomUserChangeForm
from django.contrib import messages
from crudapp.models import Blog
from django.db.models import Q

def login_view(request):
    if request.method == 'POST': 
        form = AuthenticationForm(request=request, data=request.POST) 
        if form.is_valid(): 
            username = form.cleaned_data.get('username') 
            password = form.cleaned_data.get('password') 
            user = authenticate(request=request, username=username, password=password) 
            if user is not None:
                login(request, user) 
        return redirect("home")
    else: 
        form = AuthenticationForm()
        return render(request, 'login.html', {'form':form})

def logout_view(request):
    logout(request)
    return redirect('home')

def register_view(request):
    if request.method == "POST": 
        form = RegisterForm(request.POST, request.FILES) 
        if form.is_valid(): 
            user = form.save()
            login(request, user) 
        return redirect("home")
    else:
        form = RegisterForm()
        return render(request, 'signup.html', {'form':form})

def profile_view(request, pk):
    User = get_user_model()
    u = get_object_or_404(User, pk=pk)

    posts_all = Blog.objects.all()
    posts = posts_all.filter(user=u)
    return render(request, 'profile.html', {'posts':posts, 'author':u})

def profile_update(request):
    if request.method == 'POST':
        user_change_form = CustomUserChangeForm(request.POST, request.FILES, instance = request.user)

        if user_change_form.is_valid():
            user_change_form.save()
            messages.success(request, '회원정보가 수정되었습니다.')
            return redirect('/user/profile/'+str(request.user.pk))
    else:
        user_change_form = CustomUserChangeForm(instance = request.user)
        return render(request, 'profile_update.html', {'user_change_form':user_change_form})

def profile_delete(request):
    if request.method == 'POST':
        request.user.delete()
        return redirect('home')
    return render(request, 'profile_delete.html')

@login_required
def follow(request, pk):
    User = get_user_model()
    # 팔로우 당하는 사람
    user = get_object_or_404(User, pk=pk)
    if user != request.user:
        # 팔로우를 요청한 사람 => request.user
        # 팔로우가 되어 있다면,
        if user.followers.filter(pk=request.user.pk).exists():
            # 삭제
            user.followers.remove(request.user)
        else:
            # 추가
            user.followers.add(request.user)
    return redirect('/user/profile/'+str(user.pk))

user/templates/login.html
{% extends 'base.html' %}
{% block content %}

{% load socialaccount %} 
{% providers_media_js %} <!--로그인 템플릿 파일 사용 가능.. provider에서 제공-->

<style>
    body {
        text-align: center;
        background-color: rgb(233, 231, 231);
    }
    
    .box {
        width: 40%;
        margin: 30px auto;
        background-color: white;
        padding: 50px 0px;
        border-radius: 10px;
        box-shadow: 1px 1px 3px 1px #dadce0;
    }

    input {
        border-top: none;
        border-left: none;
        border-right: none;
        border-color: lightgray;
    }

    input:focus {
        outline: none;
    }


</style>
<div class="box">
    <h3>로그인</h3>
    <form action="{%url 'user:login' %}" method="post">
        {%csrf_token%} <!-- POST 요청에 대해서만 csrf token을 발급하고 체크 -->
        {% load static %}
            {{form.as_p}}
        <a href="{% provider_login_url 'google' %}"> 
            <img src="{% static 'google.png' %}" alt="구글로그인" height="45"> 
        </a> <br><br>
        <button type="submit" class="btn btn-outline-secondary">로그인</button>
    </form>
</div>
{% endblock %}

user/templates/profile.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<style>
    body {
        background-color: rgb(233, 231, 231);
    }

    .box {
        width: 50%;
        margin: 30px auto;
        background-color: white;
        padding: 30px 0px;
        border-radius: 10px;
        box-shadow: 1px 1px 3px 1px #dadce0;
    }

    .content {
        margin: 10px auto;
        width: 80%;
        border: 1px solid lightgray;
        border-radius: 10px;
        box-shadow: 1px 1px 3px 1px #dadce0;
    }

    a {
        color: gray;
        text-decoration: none;
    }

    .info_list {
        list-style:none;
        margin: auto;
        padding: 0;
        text-align: center;
    }

    .info-profile {
        margin: 0 10px;
        padding: 0 50px 0 0;
        border : 0;
        float: left;
    }

    .info {
        margin: 0 10px;
        padding: 0;
        border : 0;
        float: left;
    }

    .info-follow {
        list-style: none;
        margin: 0 10px;
        padding: 0 0 5px 20px;
        font-weight: bold;
        text-align: left;
        color: black;
    }

    #follower_list {
        display: none;
    }

    #following_list {
        display: none;
    }

    .profilePic {
        width: 70px;
        height: 70px;
    }

    .introduce {
        color: black;
        float: left;
        margin: 5px 0 0 25px;
    }
</style>

<script type="text/javascript">
    function doDisplay(clicked_id) {
        var con = document.getElementById(clicked_id)
        if (con.style.display == 'none') {
            con.style.display = 'block';
        } else {
            con.style.display = 'none';
        }
    }
</script>

<div class="box">
    {% with user_followers=author.followers.all %}
        <ul class="list-group list-group-flush">
            <ul class="info-follow">
                {% if request.user %}
                    {% if request.user != author %}
                        {% if request.user in user_followers %}
                            <a href="{% url 'user:follow' author.pk %}">팔로우 취소</a>
                        {% else %}
                            <a href="{% url 'user:follow' author.pk %}">팔로우하기</a>
                        {% endif %}
                    {% endif %}
                {% endif %}
            </ul>
            <li class="list-group-item" style="text-align: left">
                <ul class="info_list">
                    <li class="info-profile">
                    {% if author.profilePic %}
                        <img class="profilePic" src={{author.profilePic.url}} alt='image'> &nbsp;&nbsp; {{author.username}}
                    {% else %}
                        <img class="profilePic" src= "{%static 'profile.jpg'%}" alt='image'></a> &nbsp;&nbsp; {{author.username}}
                    {% endif %}<br>   
                    </li>
                    <li class="info">
                        팔로워 <br><a href="javascript:doDisplay('follower_list')">{{ user_followers|length }}</a><br>
                        <div id="follower_list">
                            {% for follower in user_followers %}
                                <a href="{% url 'user:profile' follower.pk %}">{{follower}}</a><br>
                            {% endfor %}
                        </div>
                    </li>
                    <li class="info">
                        팔로잉 <br><a href="javascript:doDisplay('following_list')">{{ author.followings.count }}</a><br>
                        <div id="following_list">
                            {% for following in author.followings.all %}
                            <a href="{% url 'user:profile' following.pk %}">{{following}}</a><br>
                        {% endfor %}
                        </div>
                    </li>
                    <li class="info">게시물 <br>{{posts.count}}</li>
                </ul>
            </li>
        </ul>
        {% if author.introduce %}
            <span class="introduce">{{author.introduce}}</span><br>
        {% else %}
            <span class="introduce">{{author.username}}</span><br>
        {% endif %}
        <hr><br>
        <h5>작성한 글 목록</h5>
        <br>
        {% for post in posts %}
        <a href="{% url 'detail' post.id %}">
            <div class="content">
                {% if post.images %}
                <img src="{{post.images.url}}" height="280"> <!--models.py에서 사진을 보내주는 것이 아니라 url 보내주는 것임-->
                {% endif %}<br>
                {{post.body|linebreaksbr}}<br><br>
            </div>
        </a>
        {% empty %}
        아직 작성한 글이 없습니다
        {% endfor %}
    <br><br>
    {% if request.user == author %}
        <a href="{% url 'user:update' %}">회원정보 수정</a>&nbsp;&nbsp;
        <a href="{% url 'user:delete' %}">회원 탈퇴</a>
    {% endif %}
    {% endwith %}
</div>
{% endblock %}

user/templates/profile_delete.html
{% extends 'base.html' %}
{% block content %}

<h3>회원탈퇴</h3>
<form method="POST">
    {% csrf_token %}
    <p>정말로 탈퇴하시겠습니까?</p>
    <input type="submit" class="btn btn-outline-secondary" value="탈퇴">
</form>
{% endblock %}

user/templates/profile_update.html
{% extends 'base.html' %}
{% block content %}

<style>
    body {
        background-color: rgb(233, 231, 231);
    }
    
    .box {
        width: 50%;
        margin: 30px auto;
        background-color: white;
        padding: 50px 0px;
        border-radius: 10px;
        box-shadow: 1px 1px 3px 1px #dadce0;
    }

    .content {
        margin: auto;
        width: 30%;
    }

    textarea {
        width: 115%;
        height: 50px;
    } 

</style>

<div class="box">
    <h3>회원정보 수정</h3>
    <div class="content">
        <form method="post" enctype="multipart/form-data">
            {%csrf_token%} 
            {{user_change_form.as_p}}<br>
            <button type="submit" class="btn btn-outline-secondary">Submit</button>
        </form>
    </div>
</div>
{% endblock %}

user/templates/signup.html
{% extends 'base.html' %}
{% block content %}
<style>
    body {
        text-align: center;
        background-color: rgb(233, 231, 231);
    }
    
    .box {
        width: 40%;
        margin: 30px auto;
        background-color: white;
        padding: 50px 0px;
        border-radius: 10px;
        box-shadow: 1px 1px 3px 1px #dadce0;
    }

    input {
        border: 1px solid lightgray;
        border-top: none;
        border-left: none;
        border-right: none;
    }

    input:focus {
        outline: none;
    }
</style>

<div class="box">
    <h3>회원가입</h3>
    <form action="{% url 'user:signup' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
        <div>   
            <p>
                {{ field.label_tag }}
                {{ field }}
            </p>
        </div>
        {% endfor %}
        <button type="submit" class="btn btn-outline-secondary">회원가입</button>
    </form>
</div>
{% endblock %}