bookproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import crudapp.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', crudapp.views.home, name='home'),
    path('crudapp/', include('crudapp.urls')),
    path('shop/', include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('user/', include('user.urls')),
    path('accounts/', include('allauth.urls')),
    path('map/', include('map.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('', detail, name="detail"),
    path('add/<int:product_id>/', add, name="product_add"),
    path('remove/<int:product_id>/', remove, name="product_remove"),
]

map/urls.py
from django.urls import path
from .views import *

app_name = 'map'

urlpatterns = [
    path('search/', search, name="api_search"),
]

shop/urls.py
from django.urls import path
from .views import *

app_name = 'shop'

urlpatterns = [
    path('', show_list, name="list"),
    path('<int:id>/<product_slug>/', product_detail, name="product_detail"),
]

user/urls.py
from django.urls import path
from .views import *

app_name = 'user'

urlpatterns = [
    path('login/', login_view, name="login"),
    path('logout', logout_view, name="logout"),
    path('register/', register_view, name="signup"),
    path('profile/update/', profile_update, name="update"),
    path('profile/delete', profile_delete, name="delete"),
    path('profile/<int:pk>/', profile_view, name='profile'),
    path('<int:pk>/follow/', follow, name='follow'),
]

bookproject/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no">
    <title>Book Store</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=qta0qeetyw&submodules=geocoder"></script>

    <style>
      .account {
        list-style:none;
        display: inline-block;  
        text-align: center;
        margin: 0;
        padding: 0;
      }
      .nav-item2 {
        display: inline-block;
      }
      .account-link {
        color: black;
        text-decoration : none;
        padding: 5px;
      }

      .container {
        margin: 20px auto;
        text-align: center;
      }

      .navbar-brand {
        font-size: 30px;
        font-family: 'Times New Roman', Times, serif;
        margin: 8px 20px;
      }

      .profile-link {
        color: black;
        text-decoration : none;
        padding: 5px;
      }
    </style>
</head>
<body>
    {% load static %}

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'home' %}">Book Store</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'new' %}">책 추가하기</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href='{% url "shop:list" %}'>쇼핑하기</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href='{% url "cart:detail" %}'>장바구니</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href='{% url "map:api_search" %}'>장소 검색</a>
              </li>
              {% endif %}
            </ul>

            <ul class="account">
              <li class="nav-item2">
                {%if user.is_authenticated %}
                <a class="account-link" href="{% url 'user:logout' %}">로그아웃</a>
              </li>
              <li class="nav-item2">
                <div class="account-link">
                  <a class="profile-link" href="{% url 'user:profile' user.pk %}">{{user.username}} 님이 로그인 중</a>
                </div>
              </li>
                {% else %}
                <li class="nav-item2">
                  <a class="account-link" href="{% url 'user:signup' %}">회원가입</a>
                </li>
                <li class="nav-item2">
                  <a class="account-link" href="{% url 'user:login' %}">로그인</a>
                </li>
                <li class="nav-item2">
                  <div class="account-link">로그인을 해주세요.</div>
                </li>
                {% endif %}
            </ul>

            <form class="d-flex" action="{% url 'search' %}" method="post">
                {% csrf_token %}
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q" value="{{q}}">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    
</body>
</html>